### ISSUE TITLE
where is config_itlwm.plist ?

### ISSUE THREAD

**Issue by fengcms** [ansonliao/Asrock-B460m-ITX-AC-OC-EFI#6]
I can't find this file...

**Comment by ansonliao** [comment]
Please check the latest master branch, you can find `config_itlwm.plist` in `EFI --> OC`.
Please note that the file structure of `config_itlwm.plist` is not up to the latest version of `OC`, before use the configuration file, you should update the structure of `config_itlwm.plist` to you corresponding version of OC.

**Comment by fengcms** [comment]
thank you!
I can't update this file :(, But I can wait ~ :)

**Comment by Arigun** [comment]
You don't need config_itlwm.plist. Just copy 3 kext files to OC, run them by Hackintool and. restart. That's it.

**Comment by fengcms** [comment]
@Arigun thank you! let me try！

**Comment by ansonliao** [comment]
@fengcms 
Yes actually you don't need `config_itlwm.plist`, only download the Intel WiFi KEXTs from the site, and then add the KEXTs to your `config.plist`, and then install `HeliPort` in your Hackintosh, then restart

**Comment by fengcms** [comment]
@ansonliao @Arigun 
Thank you! I try to do, and I'm Success! *^_^*

**Comment by fengcms** [comment]
I want to know how to use `AirportItlwm` ? just like `itlwm` and don't need install `HeliPort`?

**Comment by ansonliao** [comment]
@fengcms 
I suggest you to do some investigation from https://openintelwireless.github.io/General/Installation.html, and you can join the Gitter channel of open intel wireless project, you can get more help of intel wifi module in hackintosh.
I think this repo about the intel wifi module patching is not up to date because I only tried it when I build this hackintosh before my Broadcom wifi card arrived.
